export const DEFAULT_SETTINGS = {
  className: 'Meine Klasse',
  xpPerLevel: 100,
  streakThresholdForBadge: 5,
  allowNegativeXP: false,
  sfxEnabled: false,
  animationsEnabled: true,
  kidModeEnabled: false,
  compactMode: false,
  shortcutsEnabled: true,
  onboardingCompleted: false,
  flags: { virtualize: false } as Record<string, boolean>,
  classStarIconKey: null,
  classMilestoneStep: 1000,
  classStarsName: 'Stern',
  avatarStageThresholds: [3, 6] as [number, number],
} as const;
